In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model
from word2number import w2n

In [2]:
df = pd.read_csv('hiring.csv')
df.head()

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000

In [3]:
median = df['test_score(out of 10)'].median()

df.experience = df.experience.fillna("zero")
df['test_score(out of 10)'] = df['test_score(out of 10)'].fillna(median)

df



experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    8.0                           7      72000
7     eleven                    7.0                           8      80000

In [4]:

df['experience'] = df['experience'].apply(lambda x: w2n.word_to_num(x) if isinstance(x, str) else x)

df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    8.0                           7      72000
7          11                    7.0                           8      80000

In [21]:
X = df[['experience' , 'test_score(out of 10)' , 'interview_score(out of 10)']]
X

experience  test_score(out of 10)  interview_score(out of 10)
0           0                    8.0                           9
1           0                    8.0                           6
2           5                    6.0                           7
3           2                   10.0                          10
4           7                    9.0                           6
5           3                    7.0                          10
6          10                    8.0                           7
7          11                    7.0                           8

In [22]:
Y = df[['salary($)']]
Y

salary($)
0      50000
1      45000
2      60000
3      65000
4      70000
5      62000
6      72000
7      80000

In [5]:
reg = linear_model.LinearRegression()
reg.fit(df[['experience' , 'test_score(out of 10)' , 'interview_score(out of 10)']], df['salary($)'])

LinearRegression()

In [6]:
reg.predict([[2, 9, 6]])

C:\Users\Muhammad Usman\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53205.96797671])

In [7]:
reg.coef_

array([2812.95487627, 1845.70596798, 2205.24017467])

In [8]:
reg.intercept_

17737.263464337688

In [9]:
2812.95487627*2 + 1845.70596798*9 + 2205.24017467*6 + 17737.263464337688


53205.96797671769

In [10]:
reg.predict([[12, 10, 10]])

C:\Users\Muhammad Usman\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([92002.18340611])

In [11]:
reg.predict([[20+1, 10, 10]])

C:\Users\Muhammad Usman\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([117318.77729258])

In [12]:
import joblib 

In [13]:
joblib.dump(reg,'joblib_model')

['joblib_model']

In [14]:
import joblib

In [15]:
new = joblib.load('joblib_model')
new

LinearRegression()

In [16]:
new.predict([[21, 10 , 10]])

C:\Users\Muhammad Usman\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([117318.77729258])

In [17]:
new.intercept_

17737.263464337688

In [24]:
from sklearn.model_selection import train_test_split
X_train , X_test, y_train, y_test  = train_test_split(X,Y, test_size = 0.2)

In [24]:
X_train

experience  test_score(out of 10)  interview_score(out of 10)
2           5                    6.0                           7
3           2                   10.0                          10
6          10                    8.0                           7
7          11                    7.0                           8
5           3                    7.0                          10
0           0                    8.0                           9

In [25]:
new.intercept_

17737.263464337688